const enemies = [
  {
    name: "Dicey Jones",
    sides: [1, 2, 1, 1, 2, 1],
    mainbg: "bg-green-800",
    pipbg: "bg-white",
    ship: "enemy1.png",
  },
  {
    name: "Captain Pipwash",
    sides: [1, 2, 2, 2, 2, 1],
    mainbg: "bg-gray-300",
    pipbg: "bg-red-700",
    ship: "enemy9.png",
  },
  {
    name: "Long Pip Silver",
    sides: [2, 3, 3, 3, 3, 2],
    mainbg: "bg-purple-800",
    pipbg: "bg-white",
    ship: "enemy2.png",
  },
  {
    name: "Chancelica",
    sides: [3, 3, 4, 4, 3, 3],
    mainbg: "bg-blue-300",
    pipbg: "bg-pink-700",
    ship: "enemy7.png",
  },
  {
    name: "Danny O'Dice",
    sides: [4, 4, 5, 5, 4, 4],
    mainbg: "bg-red-700",
    pipbg: "bg-green-200",
    ship: "enemy10.png",
  },
  {
    name: "Hector Pipossa",
    sides: [5, 5, 6, 6, 5, 5],
    mainbg: "bg-blue-700",
    pipbg: "bg-white",
    ship: "enemy4.png",
  },
  {
    name: "Pip Piraat",
    sides: [7, 5, 7, 6, 7, 6],
    mainbg: "bg-green-700",
    pipbg: "bg-yellow-300",
    ship: "enemy8.png",
  },
  {
    name: "Dice Sparrow",
    sides: [7, 5, 8, 8, 5, 7],
    mainbg: "bg-pink-700",
    pipbg: "bg-white",
    ship: "enemy3.png",
  },
  {
    name: "Rivers McPip",
    sides: [8, 6, 8, 8, 6, 8],
    mainbg: "bg-yellow-300",
    pipbg: "bg-purple-800",
    ship: "enemy6.png",
  },
  {
    name: "Pipbeard",
    sides: [9, 8, 9, 7, 8, 9],
    mainbg: "bg-gray-700",
    pipbg: "bg-gray-200",
    ship: "enemy5.png",
  },
]
export default enemies
